#!/bin/bash
#
# ~/bin/dwm-statusbar
#
# Status bar for dwm (parts taken from http://jasonwryan.com/)

print_song_info() {
  song_info="$(ncmpcpp --now-playing '{{{{%t Ý }%a}}|{%f}}' | head -c 50)"
  if [[ ! $song_info ]]; then
    song_info="Not playing"
  fi
  echo -ne "\x04Ü\x0D Î ${song_info}"
}

print_last_msg() {
  last_msg="$(cat $HOME/.logs/irssi_pipe)"
  echo -ne "\x05Ü\x0A Ò ${last_msg}"
}

print_mem_used() {
  mem_used="$(free -m | awk '/buffers\/cache/ {print $3}')"
  echo -ne "\x01 MEM: ${mem_used}M \x01"
}

print_volume() {
  volume="$(amixer get PCM | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"
  echo -ne "\x01 à ${volume}% "
}

print_datetime() {
  datetime="$(date "+%a %b %d - %I:%M%p")"
  echo -ne "\x02 È ${datetime} "
}

# network (see: http://dzen.geekmode.org/dwiki/doku.php?id=dzen:network-meter)
# cpu (see:https://bbs.archlinux.org/viewtopic.php?pid=661641#p661641)
rx_old=$(cat /sys/class/net/eth0/statistics/rx_bytes)
tx_old=$(cat /sys/class/net/eth0/statistics/tx_bytes)

while true; do
  # get new cpu idle and total usage
  eval $(awk '/^cpu /{print "cpu_idle_now=" $5 "; cpu_total_now=" $2+$3+$4+$5 }' /proc/stat)
  cpu_interval=$((cpu_total_now-${cpu_total_old:-0}))
  # calculate cpu usage (%)
  let cpu_used="100 * ($cpu_interval - ($cpu_idle_now-${cpu_idle_old:-0})) / $cpu_interval"

  # get new rx/tx counts
  rx_now=$(cat /sys/class/net/eth0/statistics/rx_bytes)
  tx_now=$(cat /sys/class/net/eth0/statistics/tx_bytes)
  # calculate the rate (K) and total (M)
  let rx_rate=($rx_now-$rx_old)/1024
  let tx_rate=($tx_now-$tx_old)/1024
  #  let rx_total=$rx_now/1048576
  #  let tx_total=$tx_now/1048576

  # output vars
  print_cpu_used() { printf "%-12b" "\x01 CPU: ${cpu_used}%"; }
  print_rx_rate() { printf "%-13b" "Ý ${rx_rate}K"; }
  print_tx_rate() { printf "%-12b" "Ü ${tx_rate}K"; }

  # Pipe to status bar, not indented due to printing extra spaces/tabs
  # xsetroot -name "$(print_song_info) \
  xsetroot -name "$(print_volume)$(print_datetime) "


  # reset old rates
  rx_old=$rx_now
  tx_old=$tx_now
  cpu_idle_old=$cpu_idle_now
  cpu_total_old=$cpu_total_now
  # loop stats every 1 second
  sleep 1
done
