#!/bin/bash
# Screenshot tool by Christopher Truett [chris.truett@gmail.com] "http://github.com/ctruett"
# Upload function from http://argandgahandapandpa.wordpress.com/
clear

upload() {
  if [ -n "$1" ]; then
    filename="$1"
  else
    filename=$(tempfile);
    cat > $filename;
  fi;

  curl -s --form "nickname=$(hostname)" --form \
    "image=@$filename;type=$(file --brief -L --mime-type $filename)"\
    --form "disclaimer_agree=Y" --form "mode=add" --form "Submit=Submit"\
    http://imagebin.org/index.php -w '%{redirect_url}\n'
}

if ( ! getopts ":bu" opt); then
  echo "Please select -u for URL or -b for BBcode."
fi
while getopts ":bu" opt; do
  case $opt in
    b)
      tmp=$(mktemp --suffix=".png")
      thumb="$(basename $tmp .png)-thumb.png"
      scrot -t 10 $tmp
      full=$(upload $tmp | sed -e "s^http://imagebin.org/^^g")
      tiny=$(upload "$thumb" | sed -e "s^http://imagebin.org/^^g")
      echo "The BBCode was copied to your clipboard."
      echo "[url=http://imagebin.org/index.php?mode=image&id=$full][img]http://imagebin.org/index.php?mode=image&id=$tiny[/img][/url]" | tr -d '\n' | xclip
      rm $tmp
      rm $thumb
      ;;
    u) 
      tmp=$(mktemp --suffix=".png")
      scrot $tmp
      full=$(upload $tmp | sed -e "s^http://imagebin.org/^^g")
      echo "The  url was copied to your clipboard."
      echo "http://imagebin.org/index.php?mode=image&id=$full" | tr -d '\n' | xclip
      rm $tmp
      ;;
  esac
done
