#!/bin/bash
# Screenshot tool by Christopher Truett [chris.truett@gmail.com] "http://github.com/ctruett"
# Upload function from http://argandgahandapandpa.wordpress.com/
clear
tmp=$(mktemp --suffix=".png")

upload() {
  if [ -n "$1" ]; then
    filename="$1"
  else
    filename=$(tempfile);
    cat > $filename;
  fi;

  curl -# --form "nickname=$(hostname)" --form \
    "image=@$filename;type=$(file --brief -L --mime-type $filename)"\
    --form "disclaimer_agree=Y" --form "mode=add" --form "Submit=Submit"\
    http://imagebin.org/index.php -w '%{redirect_url}\n'
}

if ( ! getopts ":bu" opt); then
  echo "Please select -u for URL or -b for BBcode."
fi
while getopts ":bu" opt; do
  case $opt in
    b)
      scrot -t 10 $tmp
      echo
      echo "BB Code mode."
      echo
      full=$(upload $tmp | sed -e "s^http://imagebin.org/^^g")
      tiny=$(upload $tmp | sed -e "s^http://imagebin.org/^^g")
      echo
      echo "The following BBCode was copied to your clipboard:"
      echo
      echo "[url=http://imagebin.org/index.php?mode=image&id=$full]"
      echo "[img]http://imagebin.org/index.php?mode=image&id=$tiny[/img]"
      echo "[/url]"
      echo
      echo "[url=http://imagebin.org/index.php?mode=image&id=$full][img]http://imagebin.org/index.php?mode=image&id=$tiny[/img][/url]" | tr -d '\n' | xclip
      ;;
    u) 
      scrot $tmp
      echo
      echo "URL mode."
      echo
      full=$(upload $tmp | sed -e "s^http://imagebin.org/^^g")
      echo
      echo "The following url was copied to your clipboard:"
      echo "http://imagebin.org/index.php?mode=image&id=$full"
      echo
      echo "http://imagebin.org/index.php?mode=image&id=$full" | tr -d '\n' | xclip
      ;;
  esac
done
